bjornbytes/lovr-docs

- examples/Billboard/main.lua
Plane currently takes materials, not textures
> Fix billboard example

- examples/Mesh/main.lua
- examples/Mesh/shader.lua
Could use some more comments, but posting this now because it demonstrates https://github.com/bjornbytes/lovr/pull/41
> Mesh example

- api/lovr/getOS.lua
Only the last commit was intended. I don't understand why all these other commits are in the pull request. You might have to manually rebase
> Add android to getos

- api/lovr/audio/Microphone/getData.lua
- api/lovr/audio/Source/seek.lua
- api/lovr/audio/Source/tell.lua
- api/lovr/data/AudioStream/append.lua
- api/lovr/data/SoundData/getBlob.lua
- api/lovr/data/TextureData/getBlob.lua
- api/lovr/data/newAudioStream.lua
Documents these changes:
* https://github.com/bjornbytes/lovr/pull/180
* https://github.com/bjornbytes/lovr/pull/193
* https://github.com/bjornbytes/lovr/commit/a5424a19321ed25da1c1f6bad753bc96fc01239d (to the best of my abilities; the code is a bit hard to read)
> Documentation for new audio APIs

- api/lovr/graphics/BufferUsage.lua
> Document the BufferUsage enumeration

- examples/Debugging/RawInput/main.lua
This is a slightly improved version of the input dump test program I've posted a couple times in Slack.
In its present form it will not work right for gesture hands or the controller PR. I can update when those are totally nailed down.
> "Raw Input" example

- examples/Interaction/Index_Hands/knuckles.lua
- examples/Interaction/Index_Hands/main.lua
Small demo of using the Index controller skeleton to animate the vr_glove models from SteamVR
> Add Interaction/Index_Hands example

- examples/Thread/main.lua
This is an example of the thread module on 0.12/0.13
> Create thread example

- guides/Simple_Lighting.md
> Tutorial first pass

- api/lovr/physics/Collider/getAngularDamping.lua
- api/lovr/physics/Collider/getLinearDamping.lua
- api/lovr/physics/Collider/setAngularDamping.lua
- api/lovr/physics/Collider/setLinearDamping.lua
- api/lovr/physics/World/getAngularDamping.lua
- api/lovr/physics/World/getLinearDamping.lua
- api/lovr/physics/World/setAngularDamping.lua
- api/lovr/physics/World/setLinearDamping.lua
The threshold default value is ATM 0.01 in code. If we keep it at this value, commit needs to be adapted.
> Describe threshold for damping setters

- examples/Locomotion/Basic_Thumbsticks/main.lua
Includes:
- smooth moving / turning / strafing
- snap turning and dashing forward
- free-flying mode (useful for developement)
> Thumbsticks locomotion example

- examples/Locomotion/Walking_In_Place/main.lua
Walk-in-place mechanics for locomotion, still fixed to ground plane.
> Walk-in-place locomotion example

- api/init.lua
- api/lovr/math/Mat4/lookAt.lua
- api/lovr/math/Mat4/target.lua
- examples/UI/Spectator_Camera/main.lua
Merge only if [relevant PU](https://github.com/bjornbytes/lovr/pull/364) is merged.
> Add targetTo() doc, fix UI/Spectator_Camera example

- api/lovr/math/Vec2/add.lua
- api/lovr/math/Vec2/distance.lua
- api/lovr/math/Vec2/div.lua
- api/lovr/math/Vec2/dot.lua
- api/lovr/math/Vec2/lerp.lua
- api/lovr/math/Vec2/mul.lua
- api/lovr/math/Vec2/sub.lua
- api/lovr/math/Vec3/add.lua
- api/lovr/math/Vec3/cross.lua
- api/lovr/math/Vec3/distance.lua
- api/lovr/math/Vec3/div.lua
- api/lovr/math/Vec3/dot.lua
- api/lovr/math/Vec3/lerp.lua
- api/lovr/math/Vec3/mul.lua
- api/lovr/math/Vec3/sub.lua
- api/lovr/math/Vec4/add.lua
- api/lovr/math/Vec4/distance.lua
- api/lovr/math/Vec4/div.lua
- api/lovr/math/Vec4/dot.lua
- api/lovr/math/Vec4/lerp.lua
- api/lovr/math/Vec4/mul.lua
- api/lovr/math/Vec4/sub.lua
I did not generate the HTML to test the output, just made sure that I follow the conventions.
> Vector ops accepting numbers for components

- guides/Simple_Lighting.md
Add vertexColor and lovrDiffuseColor to improve rendering of untextured
models. Reword two paragraphs to reflect the change.
Replace non-breaking space char (0xa0) with ordinary space.
> Improve color uniforms in lightning tutorial

- api/lovr/system/isKeyDown.lua
> Add system.isKeyDown

- api/lovr/graphics/Pass/mesh.lua
- api/lovr/physics/World/newBoxCollider.lua
- api/lovr/physics/World/newCapsuleCollider.lua
- api/lovr/physics/World/newCollider.lua
- api/lovr/physics/World/newCylinderCollider.lua
- api/lovr/physics/World/newMeshCollider.lua
- api/lovr/physics/World/newSphereCollider.lua
- api/lovr/physics/World/newTerrainCollider.lua
- examples/Physics/Terrain/main.lua
- examples/init.lua
Please test the generated page for API. I've only checked Lua code and it got a bit nested-up.
Feel free to reword anything you think is not clear.
(the `Pass:mesh` bit is a quick fix I noticed while looking up the docs structure)
> API and example for newTerrainCollider

- api/lovr/math/Mat4/unpack.lua
A small fix; Quat already has this.
> Add default for Mat4:unpack()

- api/lovr/graphics/Pass/circle.lua
The previous description was, imho, quite unclear. This should be clearer and hard to misinterpret
> Clarification on description

- examples/Effects/Stencil/conf.lua
- examples/Effects/Stencil/main.lua
Using the stencil is more complicated now than it used to be.
So, I think an example would be appropriate.
I am worried I got carried away and made the scene too complicated, but, you do need some complexity for it to be clear the stencils are doing anything at all. What is happening is explained in the comments.
This looks very trippy when you move your head around.
> Stencil example

- api/lovr/math/Vec3/set.lua
Again, this feature is on `dev` and hasn't landed on `master` yet.
> Set vec3 from direction of a quat

- guides/Getting_Started.md
I think this link should follow to original repo?
> lua language server link was broken
